apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docdirect-auth-db-data
  labels:
    io.kompose.service: docdirect-auth-db-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: hostpath
